export const demoRepositories = [
  {
    id: "demo-acme-storefront",
    fullName: "acme/storefront",
    owner: "acme",
    name: "storefront",
    defaultBranch: "main",
    settings: { enabled: true, model: "Claude 3.7 Sonnet", maxFiles: 30 },
  },
  {
    id: "demo-acme-api",
    fullName: "acme/platform-api",
    owner: "acme",
    name: "platform-api",
    defaultBranch: "main",
    settings: { enabled: true, model: "GPT-4.1", maxFiles: 25 },
  },
  {
    id: "demo-labs-dashboard",
    fullName: "acme/ops-dashboard",
    owner: "acme",
    name: "ops-dashboard",
    defaultBranch: "develop",
    settings: { enabled: false, model: "Claude 3.7 Sonnet", maxFiles: 30 },
  },
];

export const demoReviews = [
  {
    id: "demo-review-482",
    pullNumber: 482,
    pullTitle: "Add password reset flow",
    repository: "acme/platform-api",
    status: "COMPLETED",
    model: "Security researcher",
    commentCount: 2,
    createdAt: "2025-06-18T14:32:00.000Z",
  },
  {
    id: "demo-review-126",
    pullNumber: 126,
    pullTitle: "Improve product image loading states",
    repository: "acme/storefront",
    status: "COMPLETED",
    model: "Code analyzer",
    commentCount: 1,
    createdAt: "2025-06-17T10:18:00.000Z",
  },
  {
    id: "demo-review-481",
    pullNumber: 481,
    pullTitle: "Cache organization permissions",
    repository: "acme/platform-api",
    status: "IN_PROGRESS",
    model: "Security researcher",
    commentCount: 0,
    createdAt: "2025-06-18T15:04:00.000Z",
  },
  {
    id: "demo-review-124",
    pullNumber: 124,
    pullTitle: "Refactor checkout summary component",
    repository: "acme/storefront",
    status: "FAILED",
    model: "Code analyzer",
    commentCount: 0,
    createdAt: "2025-06-16T09:42:00.000Z",
  },
];

export const demoReviewDetail = {
  id: "demo-review-482",
  pullNumber: 482,
  pullTitle: "Add password reset flow",
  repository: "acme/platform-api",
  status: "COMPLETED",
  summary: "The password reset flow is well structured. I found one security issue that could allow reset tokens to be reused, plus an opportunity to make token expiry explicit.",
  model: "Security researcher",
  createdAt: "2025-06-18T14:32:00.000Z",
  comments: [
    {
      id: "finding-token-reuse",
      filePath: "src/auth/reset-password.ts",
      line: 48,
      severity: "error",
      title: "Reset token remains valid after password change",
      body: "The token is verified, but it is not invalidated after the password is updated. A captured link could be replayed until it expires. Rotate or consume the token in the same transaction as the password update.",
      problemCode: "await updatePassword(user.id, newPassword);\nreturn { success: true };",
      fixedCode: "await db.transaction(async (tx) => {\n  await tx.updatePassword(user.id, newPassword);\n  await tx.consumeResetToken(token.id);\n});\nreturn { success: true };",
    },
    {
      id: "finding-expiry",
      filePath: "src/auth/reset-password.ts",
      line: 31,
      severity: "warning",
      title: "Token expiry is not checked at the verification boundary",
      body: "Ensure the token verification query rejects expired tokens before returning the associated user. Keeping this check close to the data lookup makes it harder for future callers to accidentally skip expiry validation.",
      problemCode: "const token = await findResetToken(tokenHash);",
      fixedCode: "const token = await findValidResetToken(tokenHash, {\n  expiresAfter: new Date(),\n});",
    },
  ],
};
